[global]

UIName = MultiDungeon 6ABAHCpocalyps
Description = The Right project, developed by the Dungeon mod team (agent007412 McGuaire, Tauker The Hole and Lesnoy Gay-babay )
DllName = DXP3Mod
Playable = 1
ModFolder = MultiDungeon_Rightpocalypse 
ModVersion = 0.39
TextureFE = Art/UI/Textures/Title_winter_assault.tga
TextureIcon =
RuntimeMode = 3

DataFolder.1 = Data

RequiredMod.1 = DOWDE
RequiredMod.2 = DXP3
RequiredMod.3 = DXP2
RequiredMod.4 = WXP
RequiredMod.5 = W40k



