[global]

UIName = MultiDungeon ZQRGpocalypse 
Description = The Right project, developed by the Dungeon mod team (agent007412 McGuaire, Tauker The Hole and Lesnoy Gay-babay )
DllName = WXPMod
;; DllName = WXPMod_DCMod
Playable = 1
ModFolder = MultiDungeon_Rightpocalypse 
ModVersion = 0.28.1
TextureFE = Art/UI/Textures/Title_winter_assault.tga
TextureIcon =

DataFolder.1 = Data

RequiredMod.1 = DXP2Dummy
RequiredMod.2 = W40k



